/// Flutter icons PistolGun
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PistolGun
///      fonts:
///       - asset: fonts/PistolGun.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PistolGun {
  PistolGun._();

  static const _kFontFam = 'PistolGun';
  static const _kFontPkg = null;

  static const IconData pistol_gun = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
