/// Flutter icons WeaponDetailsIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeaponDetailsIcons
///      fonts:
///       - asset: fonts/WeaponDetailsIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WeaponDetailsIcons {
  WeaponDetailsIcons._();

  static const _kFontFam = 'WeaponDetailsIcons';
  static const _kFontPkg = null;

  static const IconData fire_rate1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magazine = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wall_penetration = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire_rate = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
